##hacerme swagger de modelos, rutas y controladores

### Crear un usuario VVVVVVVVVVVVVVVV

POST http://localhost:3000/api/auth/register
Content-Type: application/json

{
  "name": "enrique",
  "email": "enrique@gmail.com",
  "password": "pies56",
  "age": 25,
  "city": "madrid",
  "interests": ["comida", "deporte"],
  "recOffers": "true",
  "role": "user"
}

### login admin VVVVVVVVVVVVVVVVVV
GET  http://localhost:3000/api/auth/login
Content-Type: application/json

{
  "email": "yo@gmail.com",
  "password": "123456"
}

### login normal VVVVVVVVVVVVVVVVVVV
GET  http://localhost:3000/api/auth/login
Content-Type: application/json

{
  "email": "enrique@gmail.com",
  "password": "pies56"
}

### modificar un usuario 

PUT http://localhost:3000/api/user
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6ImVucmlxdWVAZ21haWwuY29tIiwicm9sZSI6InVzZXIiLCJpYXQiOjE3MTU4NjkyOTYsImV4cCI6MTcxNTg3NjQ5Nn0.axiGIAU5oddOySyARl-cYwdlqcbfhR8olBhiCEo4GWk
Content-Type: application/json

{
  "name": "Paquito",
  "age": 31,
  "city": "Pozuelo",
  "recOffers": "false"
}

### commerce con autorizacion VVVVVVVVVVVVVVVVVVV
POST http://localhost:3000/api/commerce
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6InlvQGdtYWlsLmNvbSIsInJvbGUiOiJhZG1pbiIsImlhdCI6MTcxNTg4NjYzMywiZXhwIjoxNzE1ODkzODMzfQ.3_dcFYJmT5Kqij43fmUV9WSZMCTZyZoCbDxrsKMvvcM
Content-Type: application/json

{
  "email": "comercioprueba@gmail.com",
  "name": "carrefour",
  "cif": "77777777",
  "address": "calle falsa 123",
  "phone": "667788990",
  "password": "123456"
}
### commerce sin autorizacion VVVVVVVVVVVVVVVVVV
POST http://localhost:3000/api/commerce HTTP/1.1
Content-Type: application/json

{
  "email": "jimmy@gmail.com",
  "name": "dinero",
  "cif": "121212121",
  "address": "aquel lugar",
  "phone": "987654321",
  "password": "121212121"
}

### todo el listado de commerces, sin iniciar sesion VVVVVVVVVVVVVVV
GET http://localhost:3000/api/commerce HTTP/1.1

### logIn de commerce VVVVVVVVVVVVVV
GET  http://localhost:3000/api/auth/login
Content-Type: application/json

{
  "email": "comercioprueba@gmail.com",
  "password": "123456"
}

### update de un commerce VVVVVVVVVVVVVV
PUT http://localhost:3000/api/commerce/121212121 HTTP/1.1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6InlvQGdtYWlsLmNvbSIsInJvbGUiOiJhZG1pbiIsImlhdCI6MTcxNTg3NzQ4MywiZXhwIjoxNzE1ODg0NjgzfQ.uq3YjqcRL261juN7jLQMtDnmRQS_XRbykPu8eFuNO4w
Content-Type: application/json

{
  "name": "holdersUnited upd",
  "cif": "123456",
  "address": "btcAvenue",
  "email": "holders@gmail.com",
  "phone": "61934358",
  "password": "password"
}

### borrado logico VVVVVVVVVVVVV
DELETE http://localhost:3000/api/commerce/121212121?logical=true HTTP/1.1


### borrado de un commerce VVVVVVVVVVV
DELETE http://localhost:3000/api/commerce/121212121?logical=false HTTP/1.1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6InlvQGdtYWlsLmNvbSIsInJvbGUiOiJhZG1pbiIsImlhdCI6MTcxNTg3NzQ4MywiZXhwIjoxNzE1ODg0NjgzfQ.uq3YjqcRL261juN7jLQMtDnmRQS_XRbykPu8eFuNO4w





### Crear pagina VVVVVVVVVVVVVVVV
POST http://localhost:3000/api/webpage HTTP/1.1
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6ImNvbWVyY2lvcHJ1ZWJhQGdtYWlsLmNvbSIsInJvbGUiOiJjb21tZXJjZSIsImlhdCI6MTcxNTg4NjY5NCwiZXhwIjoxNzE1ODkzODk0fQ.VDYVo-rw7Ae1Kxh1rDFBs_4WxEEe88-cID8ddxy8cYU

{
  "title": "pagina2",
  "city": "madrid",
  "summary": "pagina1",
  "text": "Lorem ipsum dolor sit amet",
  "scoring": 2,
  "numRatings": 1,
  "review": "muy buena, 10/10",
  "activity": "mucha"
}

### Editar pagina VVVVVVVVVVVVV

PUT http://localhost:3000/api/webpage/66465386618addb5ac1ac8b1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6ImV4YW1lbjFAZ21haWwuY29tIiwicm9sZSI6ImNvbW1lcmNlIiwiaWF0IjoxNzE1ODg0OTEzLCJleHAiOjE3MTU4OTIxMTN9.6sVXcNRbWD05UuhaFphn73Ci79kS7DVs1f9JOzcA5dk
Content-Type: application/json

{
  "city": "Pozuelo",
  "activity": "Restaurantes",
  "title": "comida5",
  "summary": "rbevdrgaergverfv",
  "email": "1@gmail.com"
}
### Subir imagenes a la pagina VVVVVVVVVVVVVV
POST http://localhost:3000/api/webpage/image HTTP/1.1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6ImNvbWVyY2lvcHJ1ZWJhQGdtYWlsLmNvbSIsInJvbGUiOiJjb21tZXJjZSIsImlhdCI6MTcxNTg4NjY5NCwiZXhwIjoxNzE1ODkzODk0fQ.VDYVo-rw7Ae1Kxh1rDFBs_4WxEEe88-cID8ddxy8cYU
Content-Type: multipart/form-data; boundary=Boundry

--Boundry
Content-Disposition: form-data; name="image"; filename="img.jpg"
Content-Type: image/jpg

< ./img.jpg
--Boundry--


### subir comentario VVVVVVVVVVVVVVV
POST http://localhost:3000/api/webpage/comment/66465386618addb5ac1ac8b1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6ImVucmlxdWVAZ21haWwuY29tIiwicm9sZSI6InVzZXIiLCJpYXQiOjE3MTU4ODcxMDYsImV4cCI6MTcxNTg5NDMwNn0.b3sFuUItdIhyp33kK7rijyfIwRfBq1lvZ-nmszO33pE
Content-Type: application/json

{
  "score": 3,
  "text": "normalita",
  "email_user": "jotita@gmail.com"
}

### lista con todas las paginas VVVVVVVVVVVVVV
GET http://localhost:3000/api/webpage

### encontrar pagina por ID
GET http://localhost:3000/api/webpage/66465386618addb5ac1ac8b1

### encontrar pagina por ciudad VVVVVVVVVVVVV
GET http://localhost:3000/api/webpage/madrid/true
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6InlvQGdtYWlsLmNvbSIsInJvbGUiOiJhZG1pbiIsImlhdCI6MTcxNTg4NTgxOSwiZXhwIjoxNzE1ODkzMDE5fQ.MWpmkpBHQsW-tGpftEJS4yFCK7I6lMovD9fMASJJl5k

### encontrar pagina por ciudad
GET http://localhost:3000/api/webpage/madrid/true/mucha
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6InVzdWFyaW9AZ21haWwuY29tIiwicm9sIjoidXN1YXJpbyIsImlhdCI6MTcxNTYxMzkwMSwiZXhwIjoxNzE1NjIxMTAxfQ.0BLiioc-mDQxavrNS1eS-IfMWydJt0OjOKkUt7aNEac

###eliminar pagina
DELETE http://localhost:3000/api/webpage/66465aa2e5e7ea5dbd412e57
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6InlvQGdtYWlsLmNvbSIsInJvbGUiOiJhZG1pbiIsImlhdCI6MTcxNTg4ODMxMCwiZXhwIjoxNzE1ODk1NTEwfQ.yuTveVZGZjsXaEF7aP4_0OeXTxDE0xc0aVZM70qvrXU
