### Crear un usuario

POST http://localhost:3000/api/auth/register
Content-Type: application/json

{
  "name": "yo",
  "email": "yo@gmail.com",
  "password": "123456",
  "age": 55,
  "city": "madrid",
  "interests": ["comida", "deporte"],
  "recOffers": "true",
  "role": "admin"
}

### login admin
GET  http://localhost:3000/api/auth/login
Content-Type: application/json

{
  "email": "yo@gmail.com",
  "password": "123456"
}
### login normal
GET  http://localhost:3000/api/auth/login
Content-Type: application/json

{
  "email": "paco@gmail.com",
  "password": "123456"
}

###
//modificar un usuario

PUT http://localhost:3000/api/usuario
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6InVzdWFyaW9AZ21haWwuY29tIiwicm9sIjoidXN1YXJpbyIsImlhdCI6MTcxNTMzNjA2MSwiZXhwIjoxNzE1MzQzMjYxfQ.0t5iR84eF413AD-l2ne8cFzyWYSmrFj45U9PQXPWmtM
Content-Type: application/json

{
  "nombre": "Paquito",
  "edad": 31,
  "ciudad": "Pozuelo",
  "permite_recibir_ofertas": false
}

### comercio con autorizacion
POST http://localhost:3000/api/comercio
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6ImpvcmdlQGdtYWlsLmNvbSIsInJvbCI6ImFkbWluIiwiaWF0IjoxNzE1MzMzMzY5LCJleHAiOjE3MTUzNDA1Njl9.S4yoEaTUfpDCSWVdOMK10CvwdKNW7goR48LQr7arPCg
Content-Type: application/json

{
  "email": "examen1@gmail.com",
  "password": "123477",
  "nombre": "ex",
  "CIF": "123341231",
  "direccion": "ese sitio",
  "telefono": "5678902123"
}
###
POST http://localhost:3000/api/comercio
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6ImpvcmdlQGdtYWlsLmNvbSIsInJvbCI6ImFkbWluIiwiaWF0IjoxNzE1MzMzMzY5LCJleHAiOjE3MTUzNDA1Njl9.S4yoEaTUfpDCSWVdOMK10CvwdKNW7goR48LQr7arPCg
Content-Type: application/json

{
  "email": "btc@gmail.com",
  "password": "dinerodinero",
  "nombre": "dinero",
  "CIF": "123456",
  "direccion": "aquel lugar",
  "telefono": "987654321"
}

### comercio sin autorizacion
POST http://localhost:3000/api/comercio HTTP/1.1
Content-Type: application/json

{
  "nombre": "AAAAAAAA",
  "CIF": "5678",
  "direccion": "aaaaaaa",
  "email": "aaa@gmail.com",
  "telefono": "61934339",
  "id_pagina": 2
}

### todo el listado de comercios, sin iniciar sesion
GET http://localhost:3000/api/comercio HTTP/1.1

### update de un comercio
PUT http://localhost:3000/api/comercio/123456 HTTP/1.1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6ImpvcmdlQGdtYWlsLmNvbSIsInJvbCI6ImFkbWluIiwiaWF0IjoxNzE1MzMyMTAyLCJleHAiOjE3MTUzMzkzMDJ9.uywucW72BR8bfAL4V1kWVwGuNr5qmIPT_H2k4ao7td4
Content-Type: application/json

{
  "nombre": "holdersUnited upd",
  "CIF": "123456",
  "direccion": "btcAvenue",
  "email": "holders@gmail.com",
  "telefono": "61934358",
  "password": "password"
}

### borrado logico
# DELETE http://localhost:3000/api/comercio/1234?logical=true HTTP/1.1


### borrado de un comercio
DELETE http://localhost:3000/api/comercio/123456?logical=false HTTP/1.1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6ImpvcmdlQGdtYWlsLmNvbSIsInJvbCI6ImFkbWluIiwiaWF0IjoxNzE1MjkxNTIxLCJleHAiOjE3MTUyOTg3MjF9.LqWlXHit1RGvZ2ioAVhnYyYOLh7SJ85E0jkJQfOtBQs

### logIn de comercio
GET  http://localhost:3000/api/auth/login
Content-Type: application/json

{
  "email": "examen1@gmail.com",
  "password": "123477"
}



### Crear pagina
POST http://localhost:3000/api/pagina HTTP/1.1
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6ImV4YW1lbjFAZ21haWwuY29tIiwicm9sIjoiY29tZXJjaW8iLCJpYXQiOjE3MTU2MTc2MzgsImV4cCI6MTcxNTYyNDgzOH0.BlD1-hQw_62Vr8Ks_dbcql2gb4YinDIZUoea7sRXeCU

{
  "titulo": "pagina2",
  "ciudad": "madrid",
  "resumen": "pagina1",
  "texto": "Lorem ipsum dolor sit amet",
  "imagen": ["img.png", "img.png"],
  "scoring": 2,
  "numRatings": 1,
  "review": "muy buena, 10/10",
  "actividad": "mucha"
}

###
//editar la info de una pagina
PUT http://localhost:3000/api/pagina/663d9cfb28731862985522cc
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6ImNvbWVyY2lvQGdtYWlsLmNvbSIsInJvbCI6ImNvbWVyY2lvIiwiaWF0IjoxNzE1MzEzMDM4LCJleHAiOjE3MTUzMjAyMzh9.AqoY2k0KjU2R90EFslR8nwMsVY-1ccYh7kmR9xlMavA
Content-Type: application/json

{
  "ciudad": "Pozuelo",
  "actividad": "Restaurantes",
  "titulo": "comida5",
  "resumen": "rbevdrgaergverfv",
  "email": "1@gmail.com"
}

### subir imagenes a la pagina
POST http://localhost:3000/api/pagina/imagen HTTP/1.1
Authorization: Bearer  eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6ImV4YW1lbjFAZ21haWwuY29tIiwicm9sIjoiY29tZXJjaW8iLCJpYXQiOjE3MTU2MTc2MzgsImV4cCI6MTcxNTYyNDgzOH0.BlD1-hQw_62Vr8Ks_dbcql2gb4YinDIZUoea7sRXeCU
Content-Type: multipart/form-data; boundary=Boundry

--Boundry
Content-Disposition: form-data; name="image"; filename="img.jpg"
Content-Type: image/jpg

< ./img.jpg
--Boundry--


### subir comentario
POST http://localhost:3000/api/pagina/comentario/664243049367a433331fc70f
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6InVzdWFyaW9AZ21haWwuY29tIiwicm9sIjoidXN1YXJpbyIsImlhdCI6MTcxNTYxMzkwMSwiZXhwIjoxNzE1NjIxMTAxfQ.0BLiioc-mDQxavrNS1eS-IfMWydJt0OjOKkUt7aNEac
Content-Type: application/json

{
  "score": 3,
  "texto": "normalita"
}

### lista con todas las paginas
GET http://localhost:3000/api/pagina

### encontrar pagina por ID
GET http://localhost:3000/api/pagina/664243049367a433331fc70f

### encontrar pagina por ciudad
GET http://localhost:3000/api/pagina/madrid/true
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6InVzdWFyaW9AZ21haWwuY29tIiwicm9sIjoidXN1YXJpbyIsImlhdCI6MTcxNTYxMzkwMSwiZXhwIjoxNzE1NjIxMTAxfQ.0BLiioc-mDQxavrNS1eS-IfMWydJt0OjOKkUt7aNEac

### encontrar pagina por ciudad
GET http://localhost:3000/api/pagina/madrid/true/mucha
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6InVzdWFyaW9AZ21haWwuY29tIiwicm9sIjoidXN1YXJpbyIsImlhdCI6MTcxNTYxMzkwMSwiZXhwIjoxNzE1NjIxMTAxfQ.0BLiioc-mDQxavrNS1eS-IfMWydJt0OjOKkUt7aNEac

###eliminar pagina
DELETE http://localhost:3000/api/pagina/663d9cfb28731862985522cc
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6ImNvbWVyY2lvQGdtYWlsLmNvbSIsInJvbCI6ImNvbWVyY2lvIiwiaWF0IjoxNzE1MzE0OTQzLCJleHAiOjE3MTUzMjIxNDN9.O1Rvj3xLUCYSHk5tFLOeS0f2wRwi_4SFa-XF0YlgLbU
