### Crear un usuario

POST http://localhost:3000/api/auth/register
Content-Type: application/json

{
  "name": "andres",
  "email": "adrespalugo@gmail.com",
  "password": "12332199",
  "age": 23,
  "city": "chipiona",
  "interests": ["comida", "deporte"],
  "recOffers": "true",
  "role": "user"
}

### login admin
GET  http://localhost:3000/api/auth/login
Content-Type: application/json

{
  "email": "yo@gmail.com",
  "password": "123456"
}
> {% client.global.set("tokenAdmin", response.body.token) %}

### login normal
GET http://localhost:3000/api/auth/login
Content-Type: application/json

{
  "email": "adrespalugo@gmail.com",
  "password": "12332199"
}
> {% client.global.set("tokenUser", response.body.token) %}

### modificar un usuario 

PUT http://localhost:3000/api/user
Authorization: Bearer {{tokenUser}}
Content-Type: application/json

{
  "name": "juan",
  "age": 31,
  "city": "despeñaperros",
  "recOffers": "false"
}

### commerce con autorizacion
POST http://localhost:3000/api/commerce
Authorization: Bearer {{tokenAdmin}}
Content-Type: application/json

{
  "email": "dia@gmail.com",
  "name": "dia",
  "cif": "555555555",
  "address": "calle falsa 55",
  "phone": "667222222",
  "password": "contraseña"
}
### commerce sin autorizacion
POST http://localhost:3000/api/commerce HTTP/1.1
Content-Type: application/json

{
  "email": "jimmy@gmail.com",
  "name": "dinero",
  "cif": "121212121",
  "address": "aquel lugar",
  "phone": "987654321",
  "password": "121212121"
}

### todo el listado de commerces con cif con token de admin
GET http://localhost:3000/api/commerce HTTP/1.1
Authorization: Bearer {{tokenAdmin}}

### todo el listado de commerces con token de user
GET http://localhost:3000/api/commerce HTTP/1.1
Authorization: Bearer {{tokenUser}}

### logIn de commerce
GET  http://localhost:3000/api/auth/login
Content-Type: application/json

{
  "email": "simio@gmail.com",
  "password": "password"
}
> {% client.global.set("tokenCommerce", response.body.token) %}

### update de un commerce
PUT http://localhost:3000/api/commerce HTTP/1.1
Authorization: Bearer {{tokenCommerce}}
Content-Type: application/json

{
  "name": "DIA",
  "address": "por ahí",
  "phone": "61934358",
  "password": "contraseña"
}

### borrado logico
DELETE http://localhost:3000/api/commerce/555555555?logical=true HTTP/1.1


### borrado de un commerce
DELETE http://localhost:3000/api/commerce/555555555?logical=false HTTP/1.1
Authorization: Bearer {{tokenCommerce}}



### Crear pagina
POST http://localhost:3000/api/webpage HTTP/1.1
Content-Type: application/json
Authorization: Bearer {{tokenCommerce}}

{
  "title": "pagina1",
  "city": "madrid",
  "user": "antonio gascon",
  "summary": "resumen de la pagina",
  "text": "Lorem ipsum dolor sit amet",
  "scoring": 5,
  "numRatings": 1,
  "review": "bastante buena, 8/10",
  "activity": "mucha"
}

### Editar pagina

PUT http://localhost:3000/api/webpage/6653cfe67df060a90bc6e0fb
Authorization: Bearer {{tokenCommerce}}
Content-Type: application/json

{
  "city": "Madrid",
  "activity": "Ocio nocturno",
  "title": "discoteca",
  "summary": "rbevdrgaergverfv",
  "email": "1@gmail.com"
}
### Subir imagenes a la pagina
POST http://localhost:3000/api/webpage/image HTTP/1.1
Authorization: Bearer {{tokenCommerce}}
Content-Type: multipart/form-data; boundary=Boundry

--Boundry
Content-Disposition: form-data; name="image"; filename="img.jpg"
Content-Type: image/jpg

< ./img.jpg
--Boundry--


### subir comentario
POST http://localhost:3000/api/webpage/comment/6653cfe67df060a90bc6e0fb
Authorization: Bearer {{tokenUser}}
Content-Type: application/json

{
  "score": 7,
  "text": "muy chulo"
}

### lista con todas las paginas con cif
GET http://localhost:3000/api/webpage
Authorization: Bearer {{tokenAdmin}}

### lista con todas las paginas
GET http://localhost:3000/api/webpage
Authorization: Bearer {{tokenUser}}

### encontrar pagina por ID
GET http://localhost:3000/api/webpage/6653c1c71ec4d354048e09f4

### encontrar pagina por ciudad
GET http://localhost:3000/api/webpage/Madrid/true
Authorization: Bearer {{tokenUser}}

### encontrar pagina por ciudad y actividad
GET http://localhost:3000/api/webpage/coruña/mucha/true
Authorization: Bearer {{tokenUser}}

###eliminar pagina

DELETE http://localhost:3000/api/webpage/66538364922cf946a54257f9
Authorization: Bearer {{tokenCommerce}}
